### ISSUE TITLE
Uninstall hangs while deleting IAF PVCs; incomplete deletion of resources

### ISSUE THREAD

**Issue by veronicaboychuk** [IBM/cp4waiops-samples#16]
### Description
When running the uninstall script, it will hang indefinitely trying to delete `data-iaf-system-elasticsearch-es-aiops-0`.
The hanging issue is due to IAF PVC deletion occurring before deletion of IAF operators.

Additionally, it does not handle the deletion two resources under the `ibm-common-services` namespace:
`nss-odlm-scope`
`odlm-scope-managedby-odlm`
(Can be seen by running `oc get namespacescopes.operator.ibm.com -n ibm-common-services`)

Notes:
Found through automated testing pipeline; some tests may have been creating user resources on the PVC causing the operator pod to hold on to it, which is a scenario that may not have been previously tested.

### Resolution
Fixes are made in [this](https://github.com/IBM/cp4waiops-samples/pull/15) pull request. IAF PVC deletion is moved after IAF operators and the two resources are added to deletion list.

**Comment by lsalazar1** [comment]
Closin
