### ISSUE TITLE
4.4 prereq script does not comply with documentation.

### ISSUE THREAD

**Issue by leleobhz** [IBM/cp4waiops-samples#227]
Hello!

The 'prereq.sh' script at line [170](https://github.com/IBM/cp4waiops-samples/blob/main/prereq-checker/4.4/prereq.sh#L170) does not create test job inside cp4aiops namespace as pointed in [IBM Cloud Pak for AIOps Documentation](https://www.ibm.com/docs/en/cloud-paks/cloud-pak-aiops/4.4.1?topic=aiops-starter-installation#exp_pull_secret). 

Manually adding entitlement key pull secret in default namespace allow 'prereq.sh' to run, but does not really check installation compliance due to this mismatch.

It's possible to fix either CloudPak documentation or this script?

Thanks!

**Comment by siyer-123** [comment]
Hi @leleobhz -- based on the details you mentioned, this situation would occur if you did not run the script in the project namespace (`cp4aiops`). 

As the [documentation of the prereq script indicates](https://github.com/IBM/cp4waiops-samples/tree/main/prereq-checker/4.4#running-the-prerequisite--upgrade-checker-tool-script), you need to confirm you are in the project namespace before running the tool. That way, the script will create the test job and run properly in general.

Could you please confirm whether you ran the script after running the `oc project` command as listed in the linked documentation above? If not, please retry.

**Comment by leleobhz** [comment]
> Hi @leleobhz -- based on the details you mentioned, this situation would occur if you did not run the script in the project namespace (`cp4aiops`). 
> 
> As the [documentation of the prereq script indicates](https://github.com/IBM/cp4waiops-samples/tree/main/prereq-checker/4.4#running-the-prerequisite--upgrade-checker-tool-script), you need to confirm you are in the project namespace before running the tool. That way, the script will create the test job and run properly in general.
> 
> Could you please confirm whether you ran the script after running the `oc project` command as listed in the linked documentation above? If not, please retry.

Hello!

Project wasn't selected and while this is pointed in the script documentation, it's not pointed on Aiops documentation, leading to a  misunderstood. This is the reason I wrote may script or IBM documentation be changed or clarified.

Also, project selection may affect afterwards oc-based commands, so this may lead to further usage issues.

**Comment by taylormgeorge91** [comment]
@siyer-123 @lsalazar1 Can the utility and documentation be updated to actively provide the namespace (project) for which the check is being executed for?

**Comment by lsalazar1** [comment]
For our 4.5.0 IBM Docs, we can make the namespace more visible. In 4.5.1 however, I can implement the following:

* A check to ensure the script is not running in default namespace
* Allow the user to pass in a param to indicate which namespace to use

**Comment by leleobhz** [comment]
> For our 4.5.0 IBM Docs, we can make the namespace more visible. In 4.5.1 however, I can implement the following:
> 
> * A check to ensure the script is not running in default namespace
> * Allow the user to pass in a param to indicate which namespace to use

I suggest you do not allow default namespace unless explicitly declared on command line param - to avoid mistakes and also allow any kind of test that need to be made on default namespace (Eg. AiOPS installed in AllNamespaces mode).

Also, thank you for you attention to this details!

**Comment by lsalazar1** [comment]
Hi @leleobhz , just an FYI we've adjusted some things on our end based on your feedback:

* I've pushed a PR to update our 4.5.1 prereq script. This new iteration of the script now has a check to ensure the script is running in a non-restricted namespace like default. You can find that PR [here](https://github.com/IBM/cp4waiops-samples/pull/239). You may pass in a `-n` option with the namespace as a parameter to force the script to run in the namespace you want to deploy CP4AIOPS
* I've worked with our doc team to ensure that -n option is also documented in our official docs. See [here](https://www.ibm.com/docs/en/cloud-paks/cloud-pak-aiops/4.5.1?topic=installation-online-console#prereq_check)

How does this look? Any questions?

**Comment by leleobhz** [comment]
Hello @lsalazar1 !

These changes sounds good to me! Thanks you so much by your attention to this issue!
