### ISSUE TITLE
Infrastructure Management Install Fails on MacOS due to incorrect usage of sleep

### ISSUE THREAD

**Issue by piers-walter-ibm** [IBM/cp4waiops-samples#53]
The installation scripts for infrastructure automation fails on the first run-through as the scripts use an 's' at the end of the sleep instruction to specify the length to sleep for. On linux this is supported but on MacOS only supports an integer after `sleep` in the shell. This causes the installation script to fail quickly as `sleep` returns instantly rather than waiting, meaning the script doesn't give the cluster time to deploy resources

To support MacOS sleep should not use an 's' after specifying the number of seconds, this will also support Linux as it default to seconds if no 's' 'm' or 'h' is put after the number.

**Comment by lsalazar1** [comment]
Closing this as PR was merged
