### ISSUE TITLE
v3.3 uninstall hangs on delete_connections

### ISSUE THREAD

**Issue by doormat18** [IBM/cp4waiops-samples#64]
We had an AIOps v3.3 install that didn't fully complete. We ran the v0.3 version of the uninstall script and for the delete_connections step it hung. There were no connections to delete, so it seems that this case is not properly handled by the script. To workaround we had to comment out the call to delete_connections and run again.

**Comment by lsalazar1** [comment]
Closing this as we are now on the 4.1 uninstall script and no reports of this issue in our board
